### ISSUE TITLE
j2py fails to convert

### ISSUE THREAD

**Issue by pmav99** [natural/java2python#22]
Hi I tried to use java2python on this [library](http://extras.springer.com/2010/978-1-84882-971-8/src) and it fails to do the convertion for some of the files.

For example, `<src/model/Dof.java>` and `<src/model/FeLoadData.java>` are converted without problems, but `<src/model/FeModelData.java>` fails with the following traceback.

I'm on Linux 64bit. and I have Installed j2py 0.5.1. 

any ideas?

P.

``` python
Traceback (most recent call last):
  File "/usr/bin/j2py", line 259, in <module>
    sys.exit(runMain(configScript(sys.argv[1:])))
  File "/usr/bin/j2py", line 57, in runMain
    return runOneOrMany(options)
  File "/usr/bin/j2py", line 83, in runOneOrMany
    return runTransform(options)
  File "/usr/bin/j2py", line 135, in runTransform
    module.walk(tree)
  File "/usr/lib/python2.7/site-packages/java2python/compiler/visitor.py", line 86, in walk
    visitor.walk(child, memo)
  File "/usr/lib/python2.7/site-packages/java2python/compiler/visitor.py", line 86, in walk
    visitor.walk(child, memo)
  File "/usr/lib/python2.7/site-packages/java2python/compiler/visitor.py", line 86, in walk
    visitor.walk(child, memo)
  File "/usr/lib/python2.7/site-packages/java2python/compiler/visitor.py", line 86, in walk
    visitor.walk(child, memo)
  File "/usr/lib/python2.7/site-packages/java2python/compiler/visitor.py", line 86, in walk
    visitor.walk(child, memo)
  File "/usr/lib/python2.7/site-packages/java2python/compiler/visitor.py", line 83, in walk
    visitor = self.accept(tree, memo)
  File "/usr/lib/python2.7/site-packages/java2python/compiler/visitor.py", line 43, in accept
    return call(node, memo)
  File "/usr/lib/python2.7/site-packages/java2python/compiler/visitor.py", line 443, in acceptFor
    if not node.firstChildOfType(tokens.BLOCK_SCOPE).children:
AttributeError: 'NoneType' object has no attribute 'children'
```

**Comment by zhouyang430** [comment]
Hi did you solve the problem? I have used java formatter and having all {} for loops still don't work. HELP!
