### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'type'

### ISSUE THREAD

**Issue by xiaoxiaoAurora** [natural/java2python#65]
Hello~ run the coomand: `python2 j2py CoNLLStreamExtractor.java`  

**Returned the following bug:**   

```
line 103:11 no viable alternative at input u'void'
line 103:11 no viable alternative at input u'void'
line 111:45 no viable alternative at input u'>'
line 186:8 no viable alternative at input u'List'
line 186:8 no viable alternative at input u'List'
line 186:43 mismatched input u'(' expecting SEMI
Traceback (most recent call last):
  File "j2py", line 259, in <module>
    sys.exit(runMain(configScript(sys.argv[1:])))
  File "j2py", line 57, in runMain
    return runOneOrMany(options)
  File "j2py", line 83, in runOneOrMany
    return runTransform(options)
  File "j2py", line 128, in runTransform
    transformAST(tree, config)
  File "D:\Python\python27\lib\site-packages\java2python\compiler\__init__.py", line 36, in transformAST
    for node in selector.walk(tree):
  File "D:\Python\python27\lib\site-packages\java2python\lang\selector.py", line 68, in walk
    for item in self.walk(child):
  File "D:\Python\python27\lib\site-packages\java2python\lang\selector.py", line 68, in walk
    for item in self.walk(child):
  File "D:\Python\python27\lib\site-packages\java2python\lang\selector.py", line 65, in walk
    for item in self(tree):
  File "D:\Python\python27\lib\site-packages\java2python\lang\selector.py", line 163, in __call__
    if tree.token.type == self.key:
AttributeError: 'NoneType' object has no attribute 'type'
```

Best wishes and good luck to you!

**Comment by YyHou** [comment]
I met the same problem.

**Comment by zhouyang430** [comment]
hi have you solve the problem?

**Comment by xiaoxiaoAurora** [comment]
> hi have you solve the problem?

No, I haven't.

**Comment by leaderiop** [comment]
i have the same probleme

**Comment by bunmalik** [comment]
Please I have the same problem, has it been resolved
